function varargout = freezeColorbar(hcb)

colors = colormap;

ghcb  = get(hcb);
CData = ind2rgb(get(ghcb.Children,'CData'),colors);
XData = get(ghcb.Children,'XData');
YData = get(ghcb.Children,'YData');
% Move ticks because IMAGESC draws them like centered pixels:
XTick = ghcb.XTick;
YTick = ghcb.YTick;
if ~isempty(XTick)
	XTick = XTick(1:end-1) + diff(XTick(1:2))/2;
end
if ~isempty(YTick)
	YTick = YTick(1:end-1) + diff(YTick(1:2))/2;
end
% Hides the colorbar:
set(hcb, 'Visible', 'Off')
% Generates other colorbar:
% hcb = axes('Position',ghcb.Position);
hcb = copyobj(hcb, ghcb.Parent);
% delete(ghcb.Children)
hold on
hcbim = image(XTick,YTick,CData,'Parent',hcb); axis tight
hold off
set(hcbim,...
	'HitTest','off',...
	'Interruptible','off',...
	'SelectionHighlight','off',...
	'XData',XData,...
	'YData',YData,...
	'Tag','TMW_COLORBAR')
set(hcb,...
	'Position',ghcb.Position,...
	'Location',ghcb.Location,...
	'XAxisLocation',ghcb.XAxisLocation,...
	'YAxisLocation',ghcb.YAxisLocation,...
	'XLim',ghcb.XLim,...
	'YLim',ghcb.YLim,...
	'XDir',ghcb.XDir,...
	'YDir',ghcb.YDir,...
	'XTick',ghcb.XTick,...
	'YTick',ghcb.YTick,...
	'XTickLabel',ghcb.XTickLabel,...
	'YTickLabel',ghcb.YTickLabel,...
 	'ButtonDownFcn',@resetCurrentAxes,...
	'Interruptible','off',...
	'ActivePositionProperty',ghcb.ActivePositionProperty,...
	'Tag','Colorbar')

if nargout == 1
	varargout{1} = hcb;
end